# Generated by Django 5.2.1 on 2025-05-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
